### PR TITLE
Peripheral: Add dev for installing requirements

### PR DESCRIPTION
**Pull request by khornberg**

### CODE REVIEW

**Comment by khornberg** [comment]
Broke because of https://github.com/kohsuke/github-api/issues/387

**Comment by madisona** [comment]
We've tried hard to remove django from this project.. there's absolutely
nothing that needs it

**Comment by khornberg** [comment]
Django was added as our typical egg projects run under python 2 and 3 via `tox` which assumes that Django is available. This adds Django to the ci requirements and should not be installed via a normal installation.

**Comment by madisona** [comment]
its not worth the distraction of incorporating the changes... but about a year ago I forked this, refactored to remove the legacy `djcopybook` and started the library at the top level of `fixedwidth`. 

I also added travis-ci integration for open-source build visibility
https://github.com/madisona/django-copybook/tree/travis-integration
https://travis-ci.org/madisona/django-copybook

**Pull request merged**
